apiVersion: apps/v1
kind: Deployment
metadata:
  name: myspringwebapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myspringwebapp
  template:
    metadata:
      labels:
        app: myspringwebapp
    spec:
      containers:
      - name: myspringwebapp
        image: acrnayyar.azurecr.io/nayyarshadab001
        ports:
        - containerPort: 8443
      
            
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: myspringwebapp-svc
spec:
  selector:
    app: myspringwebapp
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: LoadBalancer
