apiVersion: apps/v1
kind: Deployment
metadata:
  name: myspringwebapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myspringwebapp
  template:
    metadata:
      labels:
        app: myspringwebapp
    spec:
      containers:
      - name: myspringwebapp
        image: acrnayyar.azurecr.io/nayyarshadab001
        volumeMounts:
        - mountPath: /nayyar-folder
          name: azurefileshares
        ports:
        - containerPort: 8080
      volumes:
        - name: azurefileshares
          azureFile:
            secretName: storage-secret
            shareName: nayyar-folder
            readOnly: false
      
            
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: myspringwebapp-svc
spec:
  selector:
    app: myspringwebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myspringwebapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
   
spec:
  ingressClassName: nginx
  rules:
  - host: myspringwebapp.nayyar.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myspringwebapp-svc
            port:
              number: 80
